<?php
if (empty($_SESSION['admin']) || ($_SESSION['role'] ?? '') !== 'admin') return;
if (empty($_SESSION['plugin_csrf'])) $_SESSION['plugin_csrf'] = bin2hex(random_bytes(32));
$pluginCsrf = $_SESSION['plugin_csrf'];
?>
<div class="card"><div class="card-title">插件中心库</div>
<p style="font-size:13px;color:#888;margin-bottom:16px">从授权更新对接站获取插件，校验签名和 SHA256 后一键安装。</p>
<div id="pluginCenterList"><div class="loading"><div class="spinner"></div>正在读取插件中心...</div></div></div>

<div class="card"><div class="card-title">本地上传安装</div>
<p style="font-size:13px;color:#888;margin-bottom:16px">上传 ZIP 包，包内需要包含 plugin.json 清单文件。</p>
<div style="border:2px dashed #d0d5dd;border-radius:8px;padding:40px 20px;text-align:center;cursor:pointer;background:#fafbfc" onclick="document.getElementById('pluginFile').click()">
<div style="font-size:36px;margin-bottom:8px">ZIP</div><div style="font-size:14px;color:#888">点击选择插件包</div>
<input type="file" id="pluginFile" accept=".zip" style="display:none" onchange="installLocalPlugin(this)"></div>
<div id="pluginInstallResult"></div></div>

<div class="card"><div class="card-title">插件规范</div>
<p style="font-size:13px;color:#666;line-height:1.8">目录：<code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">plugins/插件名/plugin.json</code><br>
格式：<code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">{"id":"plugin_id","name":"插件名","version":"1.0.0","description":"说明","author":"作者","type":"tool"}</code></p></div>

<script>
var pluginCsrfToken = <?= json_encode($pluginCsrf, JSON_UNESCAPED_UNICODE) ?>;
function fmtSize(n){n=Number(n||0);if(n>1048576)return(n/1048576).toFixed(2)+' MB';return(n/1024).toFixed(1)+' KB'}
function authStatusText(a){if(!a)return'';if(a.banned||a.status==='banned')return'已封禁';if(a.status==='expired')return'已过期';return'正常'}
function renderPluginAuth(a){if(!a)return'';var rows=['授权域名：'+esc(a.domain||'-')];if(a.qq)rows.push('绑定 QQ：'+esc(a.qq));if(a.permanent)rows.push('授权时长：永久');else if(a.expires_at)rows.push('到期时间：'+esc(a.expires_at));if(a.days_left!==null&&a.days_left!==undefined)rows.push('剩余天数：'+esc(String(a.days_left))+' 天');rows.push('授权状态：'+esc(authStatusText(a)));return '<div class="msg" style="display:block;margin-bottom:12px">授权信息<br>'+rows.join('<br>')+'</div>'}
function renderPluginCenter(list,auth){var html=renderPluginAuth(auth)+'<table><thead><tr><th>插件</th><th>版本</th><th>说明</th><th>大小</th><th>发布时间</th><th>操作</th></tr></thead><tbody>';html+=list.map(function(p){var installed=!!p.installed;var canUpdate=!!p.update_available;var version='v'+esc(p.version||'?');if(installed&&p.installed_version)version='<span style="color:#888">本地 v'+esc(p.installed_version)+'</span><br><strong>远端 '+esc(version)+'</strong>';var action=canUpdate?'<button class="btn btn-primary btn-sm plugin-update-btn" data-id="'+esc(p.id||p.plugin_id||'')+'" data-name="'+esc(p.name||p.plugin_id||'')+'" data-local="'+esc(p.installed_version||'')+'" data-remote="'+esc(p.version||'')+'">更新</button>':(installed?'<span class="badge badge-admin">已安装</span>':'<button class="btn btn-sm plugin-install-btn" data-id="'+esc(p.id||p.plugin_id||'')+'" data-name="'+esc(p.name||p.plugin_id||'')+'">一键安装</button>');return '<tr><td><strong>'+esc(p.name||p.plugin_id)+'</strong><br><span style="font-size:12px;color:#999">'+esc(p.plugin_id||'')+'</span></td><td>'+version+'</td><td style="color:#777;font-size:12px;max-width:300px">'+esc(p.description||p.changelog||'')+'</td><td>'+fmtSize(p.size)+'</td><td>'+esc(p.published_at||'')+'</td><td>'+action+'</td></tr>'}).join('');html+='</tbody></table>';return html}
function bindPluginButtons(){document.querySelectorAll('.plugin-install-btn').forEach(function(btn){btn.onclick=function(){installRemotePlugin(this.getAttribute('data-id'),this.getAttribute('data-name'),false)}});document.querySelectorAll('.plugin-update-btn').forEach(function(btn){btn.onclick=function(){installRemotePlugin(this.getAttribute('data-id'),this.getAttribute('data-name'),true,this.getAttribute('data-local'),this.getAttribute('data-remote'))}})}
function loadPluginCenter(){var el=document.getElementById('pluginCenterList');el.innerHTML='<div class="loading"><div class="spinner"></div>正在读取插件中心...</div>';fetch('../api/index.php?source=plugin_center_list').then(r=>r.json()).then(function(d){if(!d.success){el.innerHTML='<div class=err>'+esc(d.error||'读取失败')+'</div>';return}if(!d.data.length){el.innerHTML=renderPluginAuth(d.authorization)+'<div style="text-align:center;padding:28px;color:#aaa">插件中心暂无插件</div>';return}el.innerHTML=renderPluginCenter(d.data,d.authorization);bindPluginButtons()}).catch(function(){el.innerHTML='<div class=err>读取插件中心失败</div>'})}
function installRemotePlugin(id,name,isUpdate,localVersion,remoteVersion){var text=isUpdate?'确认更新插件「'+name+'」？\n\n本地版本：'+(localVersion||'-')+'\n远端版本：'+(remoteVersion||'-'):'确认安装插件「'+name+'」？';if(!confirm(text))return;var el=document.getElementById('pluginCenterList');el.innerHTML='<div class="loading"><div class="spinner"></div>'+(isUpdate?'正在下载并更新插件...':'正在下载并安装插件...')+'</div>';fetch('../api/index.php?source='+(isUpdate?'plugin_center_update':'plugin_center_install'),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':pluginCsrfToken},body:JSON.stringify({id:id,update:!!isUpdate})}).then(r=>r.json()).then(function(d){if(d.success){var backup=d.data.backup_dir?'<br>备份目录：'+esc(d.data.backup_dir):'';el.innerHTML='<div class=msg style=display:block>插件「'+esc((d.data.manifest&&d.data.manifest.name)||d.data.name)+'」'+(isUpdate?'更新':'安装')+'成功'+backup+'，正在跳转...</div>';setTimeout(function(){window.location.href='?p=plugins'},1400)}else{el.innerHTML='<div class=err>'+esc(d.error||(isUpdate?'更新失败':'安装失败'))+'</div><div style="margin-top:12px"><button class="btn btn-sm" onclick="loadPluginCenter()">重新加载</button></div>'}}).catch(function(){el.innerHTML='<div class=err>网络错误</div>'})}
function installLocalPlugin(i){var f=i.files[0];if(!f)return;var el=document.getElementById('pluginInstallResult');el.innerHTML='<div class=loading><div class=spinner></div>安装中...</div>';var fd=new FormData();fd.append('file',f);fd.append('csrf',pluginCsrfToken);fetch('../api/index.php?source=plugin_install',{method:'POST',body:fd}).then(r=>r.json()).then(function(d){if(d.success){el.innerHTML='<div class=msg style=display:block>插件「'+esc((d.data.manifest&&d.data.manifest.name)||d.data.name)+'」安装成功，正在跳转...</div>';setTimeout(function(){window.location.href='?p=plugins'},1200)}else el.innerHTML='<div class=err>'+esc(d.error||'安装失败')+'</div>'}).catch(function(){el.innerHTML='<div class=err>网络错误</div>'})}
loadPluginCenter();
</script>
