<?php if (empty($_SESSION['admin']) || $_SESSION['role'] !== 'admin') return; ?>
<div id="saveMsgPlugin" class="msg">✓ 保存成功</div>
<div class="card"><div class="card-title">📋 已安装插件</div><div id="pluginList"><div class="loading"><div class="spinner"></div>加载中...</div></div></div>
<div id="pluginSettingsArea"></div>
<div style="text-align:center;margin-top:8px;display:none" id="pluginSaveBtnWrap">
<button class="btn btn-primary" onclick="savePluginConfig()" style="padding:12px 48px">💾 保存插件设置</button></div>
<script>
function loadPluginList(){fetch('../api/index.php?source=plugin_list').then(r=>r.json()).then(function(d){var el=document.getElementById('pluginList');if(!d.success){el.innerHTML='<div class=err>'+d.error+'</div>';return}if(!d.data.length){el.innerHTML='<div style="text-align:center;padding:20px;color:#aaa">暂无插件</div>';return}el.innerHTML='<table><thead><tr><th>名称</th><th>版本</th><th>类型</th><th>说明</th><th>操作</th></tr></thead><tbody>'+d.data.map(function(p){return '<tr><td><strong>'+esc(p.manifest?.name||p.name)+'</strong></td><td>v'+esc(p.manifest?.version||'?')+'</td><td>'+(p.manifest?.type==='service'?'服务':'工具')+'</td><td style=color:#888;font-size:12px>'+esc(p.manifest?.description||'')+'</td><td><button class="btn btn-sm" onclick="if(confirm(\'确定卸载？\')){fetch(\'../api/index.php?source=plugin_delete&name='+encodeURIComponent(p.name)+'\').then(r=>r.json()).then(function(d2){if(d2.success)loadPluginList();else alert(d2.error)}).catch(function(){alert(\'网络错误\')})}">卸载</button></td></tr>'}).join('')+'</tbody></table>';renderPluginSettings(d.data.map(function(p){return p.name}))}).catch(function(){document.getElementById('pluginList').innerHTML='<div class=err>加载失败</div>'})}
function renderPluginSettings(names){var a=document.getElementById('pluginSettingsArea');var h='';if(names.indexOf('ip')>=0)h+='<div class=card><div class=card-title>⚙ IP 定位设置</div><div class=form-group><label>数据源</label><div id=ipSourcesList></div></div></div>';if(names.indexOf('weather')>=0)h+='<div class=card><div class=card-title>⚙ 天气查询设置</div><div class=form-group><label>高德地图 API Key</label><input type=text id=amapKey placeholder="输入高德地图Key" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"><div class=form-hint>用于天气查询，可在 console.amap.com 获取</div></div></div>';if(names.indexOf('icp')>=0)h+='<div class=card><div class=card-title>⚙ ICP 备案设置</div><div class=form-group><label>Host</label><input type=text id=icpApi placeholder="" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"><div class=form-hint>只需填写协议+域名+端口，后面路径自动拼接</div></div></div>';a.innerHTML=h;document.getElementById('pluginSaveBtnWrap').style.display=h?'':'none';loadPluginCfg()}
function loadPluginCfg(){fetch('../api/index.php?source=file_config').then(r=>r.json()).then(function(d){if(!d.success)return;var ipEl=document.getElementById('ipSourcesList');if(ipEl&&d.data.ip_sources){ipEl.innerHTML=Object.entries(d.data.ip_sources).map(function(e){return'<div class=toggle-wrap><div><div class=toggle-label>'+esc(e[1].name)+'</div>'+(e[1].note?'<div style=font-size:11px;color:#999>'+esc(e[1].note)+'</div>':'')+'</div><button class="toggle '+(e[1].enabled?'on':'off')+'" onclick="var t=this;t.className=\'toggle \'+(t.classList.contains(\'on\')?\'off\':\'on\')"></button></div>'}).join('')}var ak=document.getElementById('amapKey');if(ak)ak.value=d.data.amap_key||'';var ia=document.getElementById('icpApi');if(ia)ia.value=d.data.icp_api||''}).catch(function(){})}
function savePluginConfig(){var d={};var ak=document.getElementById('amapKey');if(ak)d.amap_key=ak.value;var ia=document.getElementById('icpApi');if(ia)d.icp_api=ia.value;fetch('../api/index.php?source=admin_save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(r=>r.json()).then(function(d2){if(d2.success){alert('✅ 保存成功')}else alert('保存失败：'+(d2.error||''))}).catch(function(){alert('保存失败')})}
function savePluginConfig(){var d={};d.amap_key=(document.getElementById('amapKey')||{}).value||'';d.icp_api=(document.getElementById('icpApi')||{}).value||'';d.icp_host=(document.getElementById('icpHost')||{}).value||'';fetch('../api/index.php?source=admin_save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(r=>r.json()).then(function(d2){if(d2.success){document.getElementById('saveMsgPlugin').style.display='block';setTimeout(function(){document.getElementById('saveMsgPlugin').style.display='none'},2000)}else alert('保存失败：'+(d2.error||''))}).catch(function(){alert('保存失败')})}
loadPluginList();
</script>
