<?php if (empty($_SESSION['admin']) || $_SESSION['role'] !== 'admin') return; ?>
<div id="saveMsg" class="msg">✓ 保存成功</div>
<div class="card"><div class="card-title">📁 文件上传</div><div class="form-group"><label>单文件大小限制 (MB)</label><input type="number" id="maxFileSize" min="1" max="500" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"></div></div>
<div class="card"><div class="card-title">💬 QQ 登录</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div class="form-group"><label>API 地址</label><input type="text" id="oauthApiurl" placeholder="https://u.23zo.cn/" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"></div><div class="form-group"><label>APPID</label><input type="text" id="oauthAppid" placeholder="1000" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"></div></div><div class="form-group"><label>APPKEY</label><input type="text" id="oauthAppkey" placeholder="32位密钥" style="width:100%;padding:9px 12px;border:1px solid #d0d5dd;border-radius:6px;font-size:13px;outline:none"></div></div>
<div style="text-align:center;margin-top:8px"><button class="btn btn-primary" onclick="saveSettings()" style="padding:12px 48px">💾 保存设置</button></div>
<script>
function loadSettings(){fetch('../api/index.php?source=file_config').then(r=>r.json()).then(function(d){if(!d.success)return;document.getElementById('maxFileSize').value=d.data.max_file_size_mb||50;document.getElementById('oauthApiurl').value=(d.data.oauth&&d.data.oauth.apiurl)||'';document.getElementById('oauthAppid').value=(d.data.oauth&&d.data.oauth.appid)||'';document.getElementById('oauthAppkey').value=(d.data.oauth&&d.data.oauth.appkey)||''}).catch(function(){})}
function saveSettings(){var d={};d.max_file_size_mb=parseInt(document.getElementById('maxFileSize').value)||50;d.oauth={apiurl:document.getElementById('oauthApiurl').value.trim(),appid:document.getElementById('oauthAppid').value.trim(),appkey:document.getElementById('oauthAppkey').value.trim()};fetch('../api/index.php?source=admin_save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(r=>r.json()).then(function(d2){if(d2.success){document.getElementById('saveMsg').style.display='block';setTimeout(function(){document.getElementById('saveMsg').style.display='none'},2000)}else alert('保存失败：'+(d2.error||''))}).catch(function(){alert('保存失败')})}
loadSettings();
</script>
