<?php if (empty($_SESSION['admin']) || ($_SESSION['role'] ?? '') !== 'admin') return; ?>
<div class="card"><div class="card-title">远程更新</div>
<p style="font-size:13px;color:#666;line-height:1.8;margin-bottom:16px">当前站点只会连接 <code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">up.json</code> 中配置的更新对接站，不接受任意下载地址。</p>
<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><button class="btn btn-sm" onclick="checkRemoteUpdate()">检查更新</button><button class="btn btn-primary" id="updateBtn" onclick="runRemoteUpdate()" disabled>确认并更新</button></div>
<div id="updateResult" style="margin-top:16px"></div></div>

<div class="card"><div class="card-title">配置示例</div>
<p style="font-size:13px;color:#666;line-height:1.8">在被更新的网站根目录单独放置 <code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">up.json</code>，不要覆盖 <code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">config.json</code>：<br><code style="background:#f0f2ff;padding:2px 6px;border-radius:4px">{"endpoint":"https://ddd.23zo.cn/api.php?action=latest","app":"cx_toolbox","channel":"stable","public_key":"42VUXudIMxZmssU8D2BhnNOiQQIQv4rzfAgrlvAs7N8=","max_package_mb":80,"max_extracted_mb":250,"keep_local":true,"allow_unsigned":false}</code></p></div>

<script>
var checkedUpdate = null;
function fmtSize(n){n=Number(n)||0;return n>1048576?(n/1048576).toFixed(2)+' MB':(n/1024).toFixed(1)+' KB'}
function authStatusText(a){if(!a)return'';if(a.banned||a.status==='banned')return'已封禁';if(a.status==='expired')return'已过期';return'正常'}
function renderAuth(a){if(!a)return'';var rows=['授权域名：'+esc(a.domain||'-')];if(a.qq)rows.push('绑定 QQ：'+esc(a.qq));if(a.permanent)rows.push('授权时长：永久');else if(a.expires_at)rows.push('到期时间：'+esc(a.expires_at));if(a.days_left!==null&&a.days_left!==undefined)rows.push('剩余天数：'+esc(String(a.days_left))+' 天');rows.push('授权状态：'+esc(authStatusText(a)));return '<div class="msg" style="display:block;margin-bottom:10px">授权信息<br>'+rows.join('<br>')+'</div>'}
function renderUpdate(d){var rows=['应用：'+esc(d.app),'通道：'+esc(d.channel)];if(d.current_version)rows.push('当前版本：'+esc(d.current_version));rows.push('本次更新版本：'+esc(d.version));if(d.latest_version&&d.latest_version!==d.version)rows.push('更新站最新版本：'+esc(d.latest_version));rows.push('更新包：'+esc(d.package_name)+' ('+fmtSize(d.package_size)+')','SHA256：'+esc(d.sha256),'签名：'+(d.has_signature?'已提供':'未提供'));if(d.step_update)rows.push('更新策略：本次只更新一个版本，完成后请再次检查下一版');if(d.published_at)rows.push('发布时间：'+esc(d.published_at));if(d.changelog)rows.push('更新说明：<br>'+esc(d.changelog).replace(/\n/g,'<br>'));return renderAuth(d.authorization)+'<div class="msg" style="display:block">已读取更新站<br>'+rows.join('<br>')+'</div>'}
function checkRemoteUpdate(){var result=document.getElementById('updateResult');document.getElementById('updateBtn').disabled=true;checkedUpdate=null;result.innerHTML='<div class="loading"><div class="spinner"></div>正在读取更新站...</div>';fetch('../api/index.php?source=update_check',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.json()).then(function(d){if(!d.success){result.innerHTML='<div class="err">'+esc(d.error||'检查失败')+'</div>';return}checkedUpdate=d.data;document.getElementById('updateBtn').disabled=false;result.innerHTML=renderUpdate(d.data)}).catch(function(){result.innerHTML='<div class="err">网络错误或服务器超时</div>'})}
function runRemoteUpdate(){var result=document.getElementById('updateResult');if(!checkedUpdate){result.innerHTML='<div class="err">请先检查更新</div>';return}var msg='确认更新到 '+checkedUpdate.version+'？\n\n更新包：'+checkedUpdate.package_name+'\nSHA256：'+checkedUpdate.sha256;if(!confirm(msg))return;var btn=document.getElementById('updateBtn');btn.disabled=true;btn.textContent='更新中...';result.innerHTML='<div class="loading"><div class="spinner"></div>正在下载、校验、备份并覆盖文件...</div>';fetch('../api/index.php?source=update_apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true,expected_version:checkedUpdate.version,expected_sha256:checkedUpdate.sha256})}).then(r=>r.json()).then(function(d){btn.textContent='确认并更新';btn.disabled=false;if(!d.success){result.innerHTML='<div class="err">'+esc(d.error||'更新失败')+'</div>';return}var skipped=(d.data.skipped||[]).slice(0,8).map(esc).join('<br>');result.innerHTML='<div class="msg" style="display:block">更新完成<br>当前版本：'+esc((d.data.version&&d.data.version.version)||'-')+'<br>已覆盖文件：'+(d.data.applied||[]).length+' 个<br>跳过文件：'+(d.data.skipped||[]).length+' 个<br>备份目录：'+esc(d.data.backup_dir||'-')+'<br>更新包：'+esc(d.data.saved_as)+' ('+fmtSize(d.data.size)+')</div>'+(skipped?'<div class="form-hint" style="margin-top:8px">跳过示例：<br>'+skipped+'</div>':'')}).catch(function(){btn.textContent='确认并更新';btn.disabled=false;result.innerHTML='<div class="err">网络错误或服务器超时</div>'})}
</script>
